Решение задач 6.1, 6.2
js-tasks-ru/nodejs-20220421_alexandr-baranchugov pull request #3
Opened 2022-05-31 07:52 UTC by ABaranchugov

2022-05-31 07:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-31 07:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-04 11:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-05 02:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-05 05:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-05 18:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-05 22:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-06 03:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-06 05:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-07 04:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-07 04:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-11 18:00 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-06-14 06:18 UTC, tadjik1 requested changes
@ABaranchugov  Все сделано верно, но удалите, пожалуйста логин и пароль из гитхаба, это небезопасно

2022-06-14 06:18 UTC, tadjik1 commented on 06-mongodb-mongoose/02-rest-api/controllers/products.js
> +    .lean()
Интересное использование оператора .lean() 👍

2022-06-14 06:18 UTC, tadjik1 commented on 08-email/02-order/config.js
> +    password: 'nmnjosaozkodabxf',
Ой ей ей

2022-06-14 08:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-15 19:09 UTC, ABaranchugov commented on 08-email/02-order/config.js
> +    password: 'nmnjosaozkodabxf',
Исправил, удалил

2022-06-16 11:54 UTC, ABaranchugov commented
Добавил решение задачи 9.1

2022-06-16 11:55 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-06-17 12:57 UTC, tadjik1 approved these changes

2022-06-17 13:02 UTC, merged